#!/usr/bin/env bats
# =============================================================================
# Tests for xsv-validate.sh
# =============================================================================

# =============================================================================
# load helpers
# =============================================================================
setup_file() {
    # Resolve absolute paths once for the whole suite
    export TESTS_DIR="$( cd "$( dirname "$BATS_TEST_FILENAME" )" && pwd )"
    export REPO_ROOT="$( cd "${TESTS_DIR}/.." && pwd )"
    export SCRIPT="${REPO_ROOT}/xsv-validate.sh"
    export FIXTURES="${TESTS_DIR}/fixtures"
    export SCHEMA="${FIXTURES}/schema.json"

    # Ensure qsv is available
    if ! command -v qsv &>/dev/null; then
        echo "ERROR: qsv is not installed" >&2
        return 1
    fi

    chmod +x "${SCRIPT}"
}

setup() {
    load 'test_helper/bats-support/load'
    load 'test_helper/bats-assert/load'
    load 'test_helper/bats-file/load'

    # Each test gets its own isolated temp dir; files are copied in per-test
    export TEST_TMPDIR="$(mktemp -d)"
}

teardown() {
    # Remove output artefacts written next to every input file used in the test
    for ext in valid invalid validation-errors.tsv summary.json; do
        rm -f "${TEST_TMPDIR}/"*".${ext}"
    done
    rm -rf "${TEST_TMPDIR}"
}

# helper: copy a fixture to the per-test tmpdir
copy_fixture() {             # copy_fixture <fixture_basename>
    cp "${FIXTURES}/$1" "${TEST_TMPDIR}/$1"
    echo "${TEST_TMPDIR}/$1"
}

# =============================================================================
# 1. CLI / argument validation
# =============================================================================

@test "exits with error when no arguments are supplied" {
    run "${SCRIPT}"
    assert_failure
    assert_output --partial "No input file supplied"
}

@test "exits with error when only input file is supplied" {
    local f; f="$(copy_fixture valid.csv)"
    run "${SCRIPT}" "${f}"
    assert_failure
    assert_output --partial "No JSONschema supplied"
}

@test "exits with error when input file does not exist" {
    run "${SCRIPT}" "/nonexistent/file.csv" "${SCHEMA}"
    assert_failure
    assert_output --partial "Input file not found"
}

@test "exits with error when schema file does not exist" {
    local f; f="$(copy_fixture valid.csv)"
    run "${SCRIPT}" "${f}" "/nonexistent/schema.json"
    assert_failure
    assert_output --partial "Schema file not found"
}

@test "exits with error for unknown option" {
    local f; f="$(copy_fixture valid.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --unknown-flag
    assert_failure
    assert_output --partial "Unknown option"
}

@test "--help prints usage and exits 0" {
    run "${SCRIPT}" --help
    assert_success
    assert_output --partial "Usage"
}

@test "-h prints usage and exits 0" {
    run "${SCRIPT}" -h
    assert_success
    assert_output --partial "Usage"
}

# =============================================================================
# 2. Step 1: qsv input: comment stripping
# =============================================================================

@test "strips comment lines beginning with #" {
    local f; f="$(copy_fixture valid_with_comments.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}"
    assert_success
    # Comments must not leak into the .valid output
    assert_file_not_contains "${f}.valid" "This is a comment"
}

@test "accepts a custom comment character via --comment" {
    local f="${TEST_TMPDIR}/custom_comment.csv"
    printf '! generated by system\nid,name,email,age\n1,Alice,alice@example.com,30\n' > "${f}"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --comment '!'
    assert_success
    assert_file_not_contains "${f}.valid" "generated by system"
}

# =============================================================================
# 3. Step 1: qsv input: whitespace trimming
# =============================================================================

@test "trims leading and trailing whitespace from fields" {
    local f; f="$(copy_fixture valid_with_whitespace.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}"
    assert_success
    # After trimming '  Alice  ' -> 'Alice'; the row should be valid
    assert_file_exists "${f}.valid"
    assert_file_contains "${f}.valid" "Alice"
}

@test "trims whitespace from header names" {
    local f="${TEST_TMPDIR}/whitespace_headers.csv"
    printf '  id  ,  name  ,  email  ,  age  \n1,Alice,alice@example.com,30\n' > "${f}"
    run "${SCRIPT}" "${f}" "${SCHEMA}"
    assert_success
}

# =============================================================================
# 4. Step 1: qsv input: preamble / skip-lines
# =============================================================================

@test "skips preamble lines with --skip-lines" {
    local f; f="$(copy_fixture valid_with_preamble.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --skip-lines 2
    assert_success
    assert_file_exists "${f}.valid"
    assert_file_not_contains "${f}.valid" "Report generated"
}

# =============================================================================
# 5. Step 1: qsv input: encoding errors
# =============================================================================

@test "replaces invalid UTF-8 sequences without aborting" {
    local f="${TEST_TMPDIR}/bad_encoding.csv"
    # Write a valid header then a row with an injected 0xFF byte
    printf 'id,name,email,age\n' > "${f}"
    printf '1,\xFF Alice,alice@example.com,30\n' >> "${f}"

    run "${SCRIPT}" "${f}" "${SCHEMA}"
    # Should not exit with an unexpected error code (0 = all valid, 1 = some invalid - both OK)
    [ "${status}" -eq 0 ] || [ "${status}" -eq 1 ]
    refute_output --partial "ERROR"
}

# =============================================================================
# 6. Step 2: null replacement
# =============================================================================

# Helper: create a single-row CSV where the 'name' field contains $1,
# run the script, and assert the row ends up in .invalid (null was replaced
# -> required field now empty -> schema rejects it).
assert_null_token_replaced() {
    local token="$1"
    local f="${TEST_TMPDIR}/null_token_$(echo "${token}" | tr -dc '[:alnum:]').csv"
    printf 'id,name,email,age\n' > "${f}"
    printf '1,%s,alice@example.com,30\n' "${token}" >> "${f}"

    run "${SCRIPT}" "${f}" "${SCHEMA}"
    # Exit 1 = validation errors found (i.e. the null replacement triggered
    # the schema's "required" / "minLength" constraint)
    assert_failure 1
    assert_file_exists "${f}.invalid"
}

@test "replaces NULL with empty string" {
    assert_null_token_replaced "NULL"
}

@test "replaces null (lowercase) with empty string" {
    assert_null_token_replaced "null"
}

@test "replaces None with empty string" {
    assert_null_token_replaced "None"
}

@test "replaces NA with empty string" {
    assert_null_token_replaced "NA"
}

@test "replaces N/A with empty string" {
    assert_null_token_replaced "N/A"
}

@test "replaces NaN with empty string" {
    assert_null_token_replaced "NaN"
}

@test "replaces NIL with empty string" {
    assert_null_token_replaced "NIL"
}

@test "replaces missing with empty string" {
    assert_null_token_replaced "missing"
}

@test "replaces MISSING with empty string" {
    assert_null_token_replaced "MISSING"
}

@test "replaces unknown with empty string" {
    assert_null_token_replaced "unknown"
}

@test "replaces single dash - with empty string" {
    assert_null_token_replaced "-"
}

@test "replaces double dash -- with empty string" {
    assert_null_token_replaced "--"
}

@test "replaces triple dash --- with empty string" {
    assert_null_token_replaced "---"
}

@test "replaces .. with empty string" {
    assert_null_token_replaced ".."
}

@test "replaces ... with empty string" {
    assert_null_token_replaced "..."
}

@test "does NOT replace a partial match (e.g. 'N/A-extra')" {
    local f="${TEST_TMPDIR}/partial_null.csv"
    printf 'id,name,email,age\n1,N/A-extra,alice@example.com,30\n' > "${f}"
    run "${SCRIPT}" "${f}" "${SCHEMA}"
    # Row still has a non-empty name -> should be valid (exit 0) or invalid for
    # another reason - but the name field itself must not have been blanked
    # We just verify the script didn't hard-crash
    [ "${status}" -eq 0 ] || [ "${status}" -eq 1 ]
}

# =============================================================================
# 7. Step 3: qsv validate: result files
# =============================================================================

@test "exits 0 and produces .valid file when all rows pass schema" {
    local f; f="$(copy_fixture valid.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}"
    assert_success
    assert_file_exists "${f}.valid"
    assert_file_not_exists "${f}.invalid"
    assert_file_not_exists "${f}.validation-errors.tsv"
}

@test "exits 1 when some rows fail schema validation" {
    local f; f="$(copy_fixture mixed.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}"
    assert_failure 1
    assert_file_exists "${f}.valid"
    assert_file_exists "${f}.invalid"
    assert_file_exists "${f}.validation-errors.tsv"
}

@test "exits 1 and produces .invalid file when all rows fail" {
    local f; f="$(copy_fixture invalid.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}"
    assert_failure 1
    assert_file_exists "${f}.invalid"
    assert_file_exists "${f}.validation-errors.tsv"
}

@test "validation-errors.tsv contains row_number column" {
    local f; f="$(copy_fixture invalid.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}"
    assert_failure 1
    assert_file_contains "${f}.validation-errors.tsv" "row_number"
}

@test "validation-errors.tsv contains field column" {
    local f; f="$(copy_fixture invalid.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}"
    assert_failure 1
    assert_file_contains "${f}.validation-errors.tsv" "field"
}

@test "validation-errors.tsv contains error column" {
    local f; f="$(copy_fixture invalid.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}"
    assert_failure 1
    assert_file_contains "${f}.validation-errors.tsv" "error"
}

@test ".valid file retains the header row" {
    local f; f="$(copy_fixture valid.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}"
    assert_success
    assert_file_contains "${f}.valid" "id,name,email,age"
}

@test ".invalid file retains the header row" {
    local f; f="$(copy_fixture mixed.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}"
    assert_failure 1
    assert_file_contains "${f}.invalid" "id,name,email,age"
}

# =============================================================================
# 8. --output / -o: custom output directory
# =============================================================================

@test "-o writes output files to the specified directory" {
    local outdir="${TEST_TMPDIR}/out"
    mkdir -p "${outdir}"
    cp "${FIXTURES}/valid.csv" "${TEST_TMPDIR}/valid.csv"
    cd "${TEST_TMPDIR}"
    run "${SCRIPT}" valid.csv "${SCHEMA}" -o out
    assert_success
    assert_file_exists "${outdir}/valid.csv.valid"
}

@test "--output long form writes output files to the specified directory" {
    local outdir="${TEST_TMPDIR}/out"
    mkdir -p "${outdir}"
    cp "${FIXTURES}/valid.csv" "${TEST_TMPDIR}/valid.csv"
    cd "${TEST_TMPDIR}"
    run "${SCRIPT}" valid.csv "${SCHEMA}" --output out
    assert_success
    assert_file_exists "${outdir}/valid.csv.valid"
}

@test "-o creates the output directory when it does not exist" {
    local outdir="${TEST_TMPDIR}/new-dir"
    cp "${FIXTURES}/valid.csv" "${TEST_TMPDIR}/valid.csv"
    cd "${TEST_TMPDIR}"
    run "${SCRIPT}" valid.csv "${SCHEMA}" -o new-dir
    assert_success
    assert_dir_exists "${outdir}"
    assert_file_exists "${outdir}/valid.csv.valid"
}

@test "-o with trailing slashes still writes to the correct directory" {
    local outdir="${TEST_TMPDIR}/out"
    mkdir -p "${outdir}"
    cp "${FIXTURES}/valid.csv" "${TEST_TMPDIR}/valid.csv"
    cd "${TEST_TMPDIR}"
    run "${SCRIPT}" valid.csv "${SCHEMA}" -o "out///"
    assert_success
    assert_file_exists "${outdir}/valid.csv.valid"
}

# =============================================================================
# 8. --null: user-provided null strings
# =============================================================================

@test "--null treats a custom string as null (row becomes invalid)" {
    local f="${TEST_TMPDIR}/custom_null.csv"
    printf 'id,name,email,age\n1,SENTINEL,alice@example.com,30\n' > "${f}"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --null SENTINEL
    assert_failure 1
    assert_file_exists "${f}.invalid"
}

@test "--null requires a value" {
    local f; f="$(copy_fixture valid.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --null
    assert_failure
    assert_output --partial "--null requires a value"
}

@test "multiple --null flags all treated as null" {
    local f="${TEST_TMPDIR}/multi_null.csv"
    # Two rows — one with VAL1, one with VAL2 in the required name field
    printf 'id,name,email,age\n1,VAL1,alice@example.com,30\n2,VAL2,bob@example.com,25\n' > "${f}"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --null VAL1 --null VAL2
    assert_failure 1
    # Both rows should be invalid (null replaced in required field)
    local invalid_count
    invalid_count="$(tail -n +2 "${f}.invalid" | wc -l | tr -d ' ')"
    [ "${invalid_count}" -eq 2 ]
}

@test "--null replaces the default set (default tokens are no longer treated as null)" {
    local f="${TEST_TMPDIR}/default_override.csv"
    # 'NULL' is in the built-in default set; with --null CUSTOM it should be ignored
    printf 'id,name,email,age\n1,NULL,alice@example.com,30\n' > "${f}"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --null CUSTOM
    assert_success
    assert_file_exists "${f}.valid"
    assert_file_not_exists "${f}.invalid"
}

@test "--null with regex special characters matches the literal string" {
    local f="${TEST_TMPDIR}/regex_special.csv"
    # 'foo.bar' contains a dot; it should match only the literal string, not 'fooXbar'
    printf 'id,name,email,age\n1,foo.bar,alice@example.com,30\n2,fooXbar,foo@example.com,29\n' > "${f}"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --null "foo.bar"
    assert_failure 1
    # One should be invalid (null replaced in required field)
    local invalid_count
    invalid_count="$(tail -n +2 "${f}.invalid" | wc -l | tr -d ' ')"
    [ "${invalid_count}" -eq 1 ]
    assert_file_exists "${f}.valid"
}

@test "--null does not replace a partial match" {
    local f="${TEST_TMPDIR}/partial_custom_null.csv"
    # 'SENTINEL_extra' should NOT be replaced when --null SENTINEL is used
    printf 'id,name,email,age\n1,SENTINEL_extra,alice@example.com,30\n' > "${f}"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --null SENTINEL
    assert_success
    assert_file_exists "${f}.valid"
}

@test "--null is case-insensitive" {
    local f="${TEST_TMPDIR}/case_insenitive_null.csv"
    # 'FoObAr', 'foobar', and 'FOOBAR' should be replaced when --null fooBAR is used
    printf 'id,name,email,age\n1,FoObAr,a@b.com,24\n2,foobar,c@d.com,52\n3,FOOBAR,e@f.com,42\n4,valid,g@h.com,23\n' > "${f}"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --null fooBAR
    assert_failure 1
    # Three of four should be invalid (null replaced in required field)
    local invalid_count
    invalid_count="$(tail -n +2 "${f}.invalid" | wc -l | tr -d ' ')"
    [ "${invalid_count}" -eq 3 ]
    assert_file_exists "${f}.valid"
}

# =============================================================================
# 9. -s, --summary-file: output JSON summary file
# =============================================================================

@test "--summary-file produces a .summary.json file" {
    local f; f="$(copy_fixture valid.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --summary-file
    assert_success
    assert_file_exists "${f}.summary.json"
}

@test "-s is a short-form alias for --summary-file" {
    local f; f="$(copy_fixture valid.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}" -s
    assert_success
    assert_file_exists "${f}.summary.json"
}

@test "without --summary-file no .summary.json is created" {
    local f; f="$(copy_fixture valid.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}"
    assert_success
    assert_file_not_exists "${f}.summary.json"
}

@test "summary.json contains status_code field" {
    local f; f="$(copy_fixture valid.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --summary-file
    assert_success
    assert_file_contains "${f}.summary.json" '"status_code"'
}

@test "summary.json contains status_message field" {
    local f; f="$(copy_fixture valid.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --summary-file
    assert_success
    assert_file_contains "${f}.summary.json" '"status_message"'
}

@test "summary.json contains valid_rows field" {
    local f; f="$(copy_fixture valid.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --summary-file
    assert_success
    assert_file_contains "${f}.summary.json" '"valid_rows"'
}

@test "summary.json contains invalid_rows field" {
    local f; f="$(copy_fixture valid.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --summary-file
    assert_success
    assert_file_contains "${f}.summary.json" '"invalid_rows"'
}

@test "summary.json is valid JSON" {
    local f; f="$(copy_fixture valid.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --summary-file
    assert_success
    run python3 -c "import json, sys; json.load(open('${f}.summary.json'))"
    assert_success
}

@test "summary.json status_code is 0 when all rows are valid" {
    local f; f="$(copy_fixture valid.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --summary-file
    assert_success
    assert_file_contains "${f}.summary.json" '"status_code": 0'
}

@test "summary.json status_code is 1 when some rows fail validation" {
    local f; f="$(copy_fixture mixed.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --summary-file
    assert_failure 1
    assert_file_contains "${f}.summary.json" '"status_code": 1'
}

@test "summary.json row counts are correct for all-valid input" {
    local f; f="$(copy_fixture valid.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --summary-file
    assert_success
    # valid.csv has 2 data rows
    assert_file_contains "${f}.summary.json" '"valid_rows": 2'
    assert_file_contains "${f}.summary.json" '"invalid_rows": 0'
}

@test "summary.json row counts are correct for mixed input" {
    local f; f="$(copy_fixture mixed.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --summary-file
    assert_failure 1
    # mixed.csv has 1 valid and 1 invalid row
    assert_file_contains "${f}.summary.json" '"valid_rows": 1'
    assert_file_contains "${f}.summary.json" '"invalid_rows": 1'
}

@test "summary.json row counts are correct for all-invalid input" {
    local f; f="$(copy_fixture invalid.csv)"
    run "${SCRIPT}" "${f}" "${SCHEMA}" --summary-file
    assert_failure 1
    # invalid.csv has 2 invalid rows
    assert_file_contains "${f}.summary.json" '"valid_rows": 0'
    assert_file_contains "${f}.summary.json" '"invalid_rows": 2'
}

@test "--summary-file with -o writes the summary to the output directory" {
    local outdir="${TEST_TMPDIR}/out"
    mkdir -p "${outdir}"
    cp "${FIXTURES}/valid.csv" "${TEST_TMPDIR}/valid.csv"
    cd "${TEST_TMPDIR}"
    run "${SCRIPT}" valid.csv "${SCHEMA}" --summary-file -o out
    assert_success
    assert_file_exists "${outdir}/valid.csv.summary.json"
}


